# Generated by Django 3.0.2 on 2020-01-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parlor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parlor_logo', models.ImageField(upload_to='')),
                ('parlor_name', models.TextField()),
                ('parlor_description', models.TextField()),
                ('address', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
