# Generated by Django 3.0.2 on 2020-01-29 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parlor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parlor_logo', models.ImageField(null=True, upload_to='')),
                ('parlor_name', models.TextField()),
                ('parlor_description', models.TextField()),
                ('address', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParlorEmployee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('available_time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParlorUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('appointment_for', models.ManyToManyField(to='parlor.ParlorEmployee')),
                ('appointment_of', models.ManyToManyField(to='parlor.ParlorUser')),
            ],
        ),
    ]
